### PR TITLE
Add missing `setuptools` runtime dependency

### PR DESCRIPTION
**Pull request by eric-wieser**
See https://github.com/numba/numba/issues/4763

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by eric-wieser** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotrevisani** [comment]
Can you point where the ``pkg_resources`` is being used?

**Comment by eric-wieser** [comment]
See the linked issue

**Comment by jakirkham** [comment]
Yeah, this is [the line]( https://github.com/numba/numba/blob/8c6658375c1f8fe50e1a5ccd11d4e7bf5a8053de/numba/entrypoints.py#L3 ).

**Pull request merged**
