### PR TITLE
0.50.1

### PR DESCRIPTION
**Pull request by crusaderky**

### CODE REVIEW

**Comment by crusaderky** [comment]
@conda-forge-admin please rerender

**Comment by marcelotrevisani** [comment]
we still don't have llvmlite 0.33.0
related to https://github.com/conda-forge/llvmlite-feedstock/pull/32

**Comment by jakirkham** [comment]
Thanks @crusaderky! Unfortunately we are still blocked by `llvmlite` version `0.33.0` builds on Windows ( https://github.com/conda-forge/llvmlite-feedstock/pull/32 ). Without that, we won't be able to upgrade. If you are able to help with the Windows builds, that would be great! 😄

**Comment by jakirkham** [comment]
Sorry @marcelotrevisani. Seems we posted at that the same time 😉

**Comment by marcelotrevisani** [comment]
> Sorry @marcelotrevisani. Seems we posted at that the same time wink

:smile: 
haha, no worries! :grin:

**Comment by crusaderky** [comment]
@jakirkham would it be possible to skip the windows build for now and then repackage once it becomes available?

**Comment by crusaderky** [comment]
Also, the CI build is now using llvmlite from the pkgs/main repo. Do we *need* to use llvmlite from conda-forge?

**Comment by jakirkham** [comment]
`defaults` and `conda-forge` are likely building these in fairly different ways (though I could be wrong). This is tied to how LLVM packaging is done in both channels.

It would be nice to have all the platforms covered.

**Comment by marcelotrevisani** [comment]
Let's wait for the ``llvmlite 0.33.0``
I am optimistic that we are getting close to build that on windows :)

**Comment by step21** [comment]
Hey, so as llvmlite was for now merged without windows - would it be ok to do that here too?
Mainly as it seems that there is an error about TypeError / jitdebug which yielded only two results in projects using numba, which claimed downgrading llvmlite or using numba 0.49.1 fixed it, which does not apply here. Zero results at numba gibthub issues. And when using 0.50.1 it seems to work. (tested locally and here https://github.com/conda-forge/numba-feedstock/pull/52)

**Comment by jakirkham** [comment]
Well we only disabled Python 3.8 on Windows. Other Python and Windows combinations are still built. That said, sure I suppose we can do something similar here.

**Comment by isuruf** [comment]
This PR works fine now and is ready to be merged. (llvmlite 0.33 for win py38 is coming from defaults)

**Pull request merged**
