### PR TITLE
v0.60rc1

### PR DESCRIPTION
**Pull request by gmarkall**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by gmarkall** [comment]
@conda-forge-admin please rerender

**Comment by jakirkham** [comment]
@conda-forge-admin , please re-render

**Comment by jakirkham** [comment]
@conda-forge-admin , please re-render

**Comment by jakirkham** [comment]
@conda-forge-admin , please re-render

**Comment by jakirkham** [comment]
@conda-forge-admin , please re-render

**Comment by jakirkham** [comment]
@conda-forge-admin , please re-render

**Comment by jakirkham** [comment]
Thanks Graham! 🙏

Pushed a few changes:

* Use `llvmlite` RC channel
* Bump `llvmlite` to `0.43`
* Pull `numpy` pinning from variant files (in `.ci_support/*.yaml`)
* Drop unneeded `{{ pin_compatible('numpy') }}` ( https://github.com/conda-forge/conda-forge.github.io/issues/2156 )
* Re-render

Hopefully that clears up a few issues seen here before 🙂

**Comment by gmarkall** [comment]
Thanks @jakirkham, I was having some trouble figuring out where to go with this.

**Comment by gmarkall** [comment]
Looks like we have a couple of other issues to resolve though - a use of `np.complex_` and something to do with `__getstate__()` on an RNG instance returning `None`.

**Comment by gmarkall** [comment]
This will need a couple of Numba issues to be resolved prior to progress here:

* https://github.com/numba/numba/issues/9598
* https://github.com/numba/numba/issues/9599

**Pull request closed without merging**
