### PR TITLE
I think numpy 1.16 is now supported

### PR DESCRIPTION
**Pull request by hmaarrfk**
I think it is supported

claims that it was in 0.43.1.rc ???
https://github.com/numba/numba/pull/3826

Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
I think we just want to drop that pinning altogether. It was added as a workaround. Please see PR ( https://github.com/conda-forge/numba-feedstock/pull/23 ) for details.

**Comment by hmaarrfk** [comment]
I pinned the host dependency so as to avoid any default pinnings there. Is that not correct?

**Comment by jakirkham** [comment]
Yes, `numpy` should not be pinned in `host`.

**Comment by hmaarrfk** [comment]
lets monitor to see what it compiles with.

**Comment by jakirkham** [comment]
We might need to re-render.

**Comment by hmaarrfk** [comment]
@conda-forge-admin, please rerender

**Comment by hmaarrfk** [comment]
I'm not sure if numba deals well with such old numpy. Numpy 1.9 seems to have been pinned. lets check the builds when they finish though

**Comment by jakirkham** [comment]
Thanks @hmaarrfk :)

**Comment by jakirkham** [comment]
FWIW it looks like they are [testing against NumPy 1.9]( https://github.com/numba/numba/blob/1de3cd5a687011d90b1a26070c6fe47abdf8a2a5/.travis.yml#L15 ).

**Pull request merged**
