### PR TITLE
Rebuidl with llvmlite 0.39

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #95.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Is this ok?

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
I guess there are errors here:
```
File "../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.9/site-packages/numba/tests/test_entrypoints.py", line 207:

            def foo(x):

                return x

                ^ 
```

**Comment by henryiii** [comment]
Numba version and llvmlite version are locked. This will happen in #94.

**Pull request closed without merging**
