### PR TITLE
Rebuild python39 0 2 hb76e26

### PR DESCRIPTION
**Pull request by chrisburr**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Closes #60

### CODE REVIEW

**Comment by chrisburr** [comment]
Looks like this will be blocked for a while: https://github.com/numba/numba/issues/6345

**Comment by henryiii** [comment]
This should have happened as part of the recent 0.52 update.

**Comment by mbargull** [comment]
@henryiii, Python 3.9 is still in the "migration phase" which means only the migration PRs themselves but not other (e.g., version bump) PRs.
It's best to not close the bot PRs (e.g., gh-60) because the migration logic then thinks the migration "succeeded" (i.e., if it's just closed, not merged, it is assumed that a manual change has been made for the migration).
I've opened gh-64 for the manual migration.

**Comment by henryiii** [comment]
Sorry! I didn't see a version limit or skip so for some reason thought 0.52 supported 3.9 (which think about it, I knew better).

**Pull request closed without merging**
