### PR TITLE
Enable Windows builds

### PR DESCRIPTION
**Pull request by prisae**
I just did as suggested by @isuruf in https://github.com/conda-forge/numba-feedstock/issues/3 => Removed line 16, to see if it builds on windows or how it fails, to hopefully enable windows builds in the future.

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by prisae** [comment]
What is the reason it only builds it for Python 3.6 and 3.7, but not for 3.5? Nothing in the meta.yaml explicitly states that. I guess it has something to do with the minimum requirement of some dependencies.

**Comment by chrisburr** [comment]
> What is the reason it only builds it for Python 3.6 and 3.7, but not for 3.5?

Conda-forge only supports 2.7, 3.6 and 3.7. 3.8 will be added by #36 once it's dependencies are available.

**Comment by prisae** [comment]
Thanks. Wasn't aware of that.

**Comment by prisae** [comment]
Windows builds were originally disabled in https://github.com/conda-forge/numba-feedstock/pull/9 because of
> Currently all Windows builds either fail due to precision issues in the tests (Python 3 primarily) or they stall out during testing until CI terminates them (Python 2). Not entirely sure the issues that are causing these problems...

**Comment by prisae** [comment]
@jakirkham , do you think it would be possible to re-enable numba-builds for windows? (Asking you because you disabled it a while back.)

**Comment by marcelotrevisani** [comment]
> Windows builds were originally disabled in #9 because of
> 
> > Currently all Windows builds either fail due to precision issues in the tests (Python 3 primarily) or they stall out during testing until CI terminates them (Python 2). Not entirely sure the issues that are causing these problems...

It seems these problems ae not happening now, right?
So, can we move forward and merge it?
is that ready?

**Comment by prisae** [comment]
IMHO yes.

**Comment by jakirkham** [comment]
If it passes, it seems fine to me. The main challenge has been fixing issues that come up. So if someone can volunteer to help maintain the Windows builds here, that would be great! 😄

**Pull request merged**
