### PR TITLE
Apply tbb 2021 migration

### PR DESCRIPTION
**Pull request by chrisburr**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by chrisburr** [comment]
@conda-forge/numba For some reason the bot was failing to solve this migration but applying it by hand is working so this is ready for review

**Comment by chrisburr** [comment]
@conda-forge/numba ready for review

**Comment by henryiii** [comment]
Sorry, I missed this! What is the status?

**Comment by henryiii** [comment]
Oh, #80 is in. Okay. Sorry about the delay!

**Pull request closed without merging**
