### PR TITLE
Remove setuptools constraint

### PR DESCRIPTION
**Pull request by gmarkall**
Based on and closes #105 with the setuptools constraint removed from setup.py in an attempt to make `pip check` succeed. I expect a further patch to some tests may be required.

Closes #104 too.

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by henryiii** [comment]
Why would tests need patching? Everything should be working again after the rollback in setuptools 65.0.2 or 65.1. I could be wrong, of course, but I'd expect it to work.

**Comment by gmarkall** [comment]
> Why would tests need patching? Everything should be working again after the rollback in setuptools 65.0.2 or 65.1. I could be wrong, of course, but I'd expect it to work.

There are some tests that ensure that Numba import doesn't produce any warnings. I was concerned that the deprecation warning that suggests using setuptools < 60 might be produced by NumPy and cause this test to fail. Though, looking at the set of tests that run, we don't have a test with NumPy 1.23 in the list of configurations, so maybe we won't run into this issue :crossed_fingers:

**Comment by henryiii** [comment]
Shouldn't we have a test with NumPy 1.23? :D

**Comment by gmarkall** [comment]
Yes, we should test with NumPy 1.23 - I was thinking of following up with that later once the dust has settled here.

**Comment by jakirkham** [comment]
cc @xhochy

**Comment by gmarkall** [comment]
Seems that the PPC builds are a bit close to the time limit and some of them timed out for this PR - do we just re-run tests when this happens?

**Comment by jakirkham** [comment]
Yep have restarted those jobs

**Review by henryiii — APPROVED** [review]
LGTM, anything left?

**Comment by jakirkham** [comment]
Thanks all! 🙏

Just a note, we are still seeing `ppc64le` builds hanging on `main` ( https://github.com/conda-forge/numba-feedstock/issues/102 ).

**Pull request merged**
